pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
  - dev
  - /renovate\/.*/
skip_tags: true
max_jobs: 1
skip_commits:
 files:
   - README.md
   - CHANGELOG.md
   - .editorconfig
   - .gitignore

image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

init:
  - git config --global core.autocrlf true

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

before_build:
  - dotnet --version
  - dotnet restore --verbosity m

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false
